[build]
  # The command Netlify runs to build your site
  command = "npm run build"

  # The directory that contains the finished files (e.g., dist, build, or public)
  publish = "dist"

[build.environment]
  # You can define environment variables here
  #NODE_VERSION = "20"